---
# vars file for vcsa
site: "{{ inventory_hostname.split('.')[2] | lower }}"
domain: "{{ inventory_hostname | adsite('fqdn') }}"
digicert_url: https://cacerts.digicert.com/
root_ca_file: DigiCertGlobalRootCA.crt
interm_ca_file: DigiCertSHA2SecureServerCA.crt
datacenter: QA-DE-5A
vm_name_to_snap: vc-a-0.cc.qa-de-5.cloud.sap
vcenter_fqdn: vc-a-0.cc.qa-de-5.cloud.sap
snapshot_name: ansible_auto_snap
files:
  - "{{ inventory_hostname }}.pem"
  - "{{ inventory_hostname }}-key.pem"
... 
