#
# Role to Check vCenter services health status
# Author: Julian Wendland
#
---

- name: check vcenter services health
  hosts: localhost
  connection: local

  vars_files:
    - /home/jw/github/AnsibleRoles/vcsa/roles/vcsa.general/vault/secrets.yml

  roles:
    - { role: vcsa.general, vcenter: 10.0.20.94 }
    - { role: vcsa.service, vcenter: 10.0.20.94 }
...
