# TODO: change secrets.yml path
#
# Role to change vCenter Server certificates
# Author: Julian Wendland
#
---

- name: Change vCenter Certificates
  hosts: localhost
  connection: local
  
  handlers:
    - include: roles/vcsa.vm.snapshot/handlers/main.yml

  vars_files:
    - /home/jw/github/AnsibleRoles/vcsa/roles/vcsa.general/vault/secrets.yml
  
  roles:
    - roles/vcsa.certificate
...
