---
  - name: create vcsa snapshot before certificate change action
    vmware_guest_snapshot:
      hostname: "{{ vcenter_fqdn }}"
      username: "{{ vc_username }}"
      password: "{{ vc_password }}"
      validate_certs: no
      datacenter: "{{ datacenter }}"
      folder: "/{{ datacenter }}/vm/"
      name: "{{ vm_name_to_snap }}"
      state: present
      snapshot_name: "{{ snapshot_name }}"
    delegate_to: 127.0.0.1
...
