# Author Julian Wendland - C5318182
---
  - name: vCenter Login
    no_log: true
    uri:
      url: "https://{{ vcenter_fqdn }}/rest/com/vmware/cis/session"
      force_basic_auth: yes
      method: POST
      user: "{{ vc_username }}"
      password: "{{ vc_password }}"
      status_code: 200
      validate_certs: no
    register: login
    failed_when: login.status != 200
    delegate_to: localhost

  - name: save api token
    no_log: true
    set_fact:
      api_token: "{{ login.json['value'] }}"
...
