---
# handlers file for vcsa.vm.snapshot
#- include: vcsa/roles/vcsa.vm.snapshot/handlers/vmware_vcsa_vm_remove_snapshot.yml 
- name: remove-snapshot
  vmware_guest_snapshot:
    hostname: "{{ vc_fqdn }}"
    username: "{{ vc_username }}"
    password: "{{ vc_password }}"
    validate_certs: no
    datacenter: "{{ datacenter }}"
    folder: "/{{ datacenter }}/vm/"
    name: "{{ vm_name_to_snap }}"
    state: absent
    snapshot_name: "{{ snapshot_name }}"
  delegate_to: 127.0.0.1
...
