---
  - name: test-handlers
    debug:
      msg: "Startet Hadler"

  - name: restart-services
    uri:
      url: "https://{{ vcenter }}/rest/appliance/services/{{ serviceToRestart }}/restart"
      method: POST
      validate_certs: no
      body_format: json
      headers:
        Cookie: "{{ login.set_cookie }}"
...
