---
  - name: restart-services
    uri:
      url: "https://{{ vcenter }}/rest/appliance/services/{{ service }}/restart"
      method: POST
      validate_certs: no
      body_format: json
      headers:
        Cookie: "{{ login.set_cookie }}"
...
