---
  - name: Backup schedule already exists?
    uri:
      url: "https://jw-vcsa7.vdi.sclabs.net/rest/appliance/recovery/backup/schedules/auto_schedule"
      method: GET
      validate_certs: no
      headers:
        Cookie: "{{login.set_cookie}}"
    register: get_backup
    ignore_errors: yes  

  - name: Set Backup schedule
    uri: 
      url: "https://jw-vcsa7.vdi.sclabs.net/rest/appliance/recovery/backup/schedules/auto_schedule"
      method: POST
      validate_certs: no
      body_format: json
      body: "{{ lookup('template','backup_schedule_request_body.j2') }}"
      headers:
        Cookie: "{{login.set_cookie}}"
    when: get_backup.status == 404
...
