---
- name:  Clone a virtual machine from Linux template and customize
  vmware_guest:
    hostname: "{{ vcenter_fqdn }}"
    username: "{{ vc_username }}"
    password: "{{ vc_password }}"
    validate_certs: no
    datacenter: "{{ datacenter }}"
    state: present
    folder: /vm
    template: "{{ template }}"
    name: "{{ backup_server_hostname }}"
    networks:
      - name: "{{ network_portgroup }}"
        ip: "{{ ip_address  }}"
        netmask: "{{ netmask  }}"
        connected: yes
        start_connected: yes
    wait_for_ip_address: True
    customization:
      autologon: yes
      existing_vm: no
      hostname: "{{ backup_server_hostname }}"
      domain: "{{ guest_domain }}"
      dns_servers:
        - "{{ dns_server }}" 
  delegate_to: localhost
...

