---
  - name: Get Backup Job
    uri:
      url: "https://{{ vcenter }}/rest/appliance/recovery/backup/job"
      method: GET
      validate_certs: no
      headers:
        Cookie: "{{login.set_cookie}}"
...
